### ISSUE TITLE
--filter-trace-xdp does not work with pcap-filter

### ISSUE THREAD

**Issue by Asphaltt** [cilium/pwru#425] opened 2024-09-24 15:52 UTC
After I fixing the broken `--filter-trace-xdp`, I find that it fails to run `--filter-trace-xdp` with pcap-filter correctly, like:

```bash
# ./pwru --filter-trace-xdp --filter-func '.*udp.*' --output-limit-lines 10 icmp
2024/09/24 15:48:17 Attaching xdp progs...
2024/09/24 15:48:17 Attaching kprobes (via kprobe-multi)...
49 / 49 [--------------------------------------------------------------------------------------------------------------------------------------] 100.00% ? p/s
2024/09/24 15:48:17 Attached (ignored 0)
2024/09/24 15:48:17 Listening for events..
SKB                CPU PROCESS          NETNS      MARK/x        IFACE       PROTO  MTU   LEN   TUPLE FUNC
0xffff9a5f80600b00 6   <empty>:0        4026531840 0            ens33:2      0x0000 1500  102   192.168.241.1:55057->192.168.241.133:22(tcp) dummy(xdp)
0xffff9a5f80600b00 6   <empty>:0        4026531840 0            ens33:2      0x0000 1500  66    192.168.241.1:55057->192.168.241.133:22(tcp) dummy(xdp)
0xffff9a5f80600b00 6   <empty>:0        4026531840 0            ens33:2      0x0000 1500  66    192.168.241.1:55057->192.168.241.133:22(tcp) dummy(xdp)
0xffff9a5f80600b00 6   <empty>:0        4026531840 0            ens33:2      0x0000 1500  66    192.168.241.1:55057->192.168.241.133:22(tcp) dummy(xdp)
0xffff9a5f80600b00 6   <empty>:0        4026531840 0            ens33:2      0x0000 1500  66    192.168.241.1:55057->192.168.241.133:22(tcp) dummy(xdp)
0xffff9a5f80600b00 6   <empty>:0        4026531840 0            ens33:2      0x0000 1500  102   192.168.241.1:55057->192.168.241.133:22(tcp) dummy(xdp)
0xffff9a5f80600b00 6   <empty>:0        4026531840 0            ens33:2      0x0000 1500  66    192.168.241.1:55057->192.168.241.133:22(tcp) dummy(xdp)
0xffff9a5f80600b00 6   <empty>:0        4026531840 0            ens33:2      0x0000 1500  66    192.168.241.1:55057->192.168.241.133:22(tcp) dummy(xdp)
0xffff9a5f80600b00 6   <empty>:0        4026531840 0            ens33:2      0x0000 1500  66    192.168.241.1:55057->192.168.241.133:22(tcp) dummy(xdp)
0xffff9a5f80600b00 6   <empty>:0        4026531840 0            ens33:2      0x0000 1500  66    192.168.241.1:55057->192.168.241.133:22(tcp) dummy(xdp)
2024/09/24 15:48:17 Printed 10 events, exiting program..
2024/09/24 15:48:17 Detaching kprobes...
3 / 3 [---------------------------------------------------------------------------------------------------------------------------------------] 100.00% 21 p/s
```

**Comment by brb** [comment] 2024-10-13 14:26
Seems like duplicate of https://github.com/cilium/pwru/issues/438?

**Comment by Asphaltt** [comment] 2024-10-13 14:50
Sure, it's duplicate.

**Closed** 2024-10-16 09:44 UTC
